### ISSUE TITLE
[채팅] 채팅방 초기 생성 주소에서 새로 고침 시 채팅방 반복 생성되는 버그 fix

### ISSUE THREAD

**Issue by syulyul** [NC7-1st-TeamProject-1st-Team/2nd-sns-notification-system#329]
## 목적
> 채팅방 초기 생성 주소에서 새로 고침 시 채팅방 반복 생성되는 버그 fix
## 작업 상세 내용
- [ ] 채팅방 초기 생성 주소에서 새로 고침 시 채팅방 반복 생성되는 버그 fix
## 참고사항
이미 해당 기능에 관한 이슈가 있는 경우 링크를 첨부해주세요. ( # 입력하면 태그 가능)

**Comment by pangorithm** [comment]
node server에서 enterRoom에서 createRoom의 예외조건 추가
