### ISSUE TITLE
[채팅] 채팅방 나기기 시 채팅 리스트에서 해당 채팅방이 사라지지 않는 오류 fix

### ISSUE THREAD

**Issue by syulyul** [NC7-1st-TeamProject-1st-Team/2nd-sns-notification-system#331]
## 목적
> 채팅방 나가기 시 채팅 리스트에서 해당 채팅방이 사라지지 않는 오류 fix
## 작업 상세 내용
- [ ] 채팅방 나가기 시 채팅 리스트에서 해당 채팅방이 사라지지 않는 오류 fix
## 참고사항
이미 해당 기능에 관한 이슈가 있는 경우 링크를 첨부해주세요. ( # 입력하면 태그 가능)

**Comment by pangorithm** [comment]
백엔드에서 방 삭제 성공 응답 회신 시 리스트를 다시 로드하도록 수정
